START_IDX=0
END_IDX=16
NUM_TIMES=17
DATASET="abstracts"
TOP_X=20

HERE="/scratch2/aherzog/CLDA/scripts/ICDM"

HOLDOUT_MOD=5
HOLDOUT_IDX=0

LOCAL_TOPICS=50
GLOBAL_TOPICS=20

PLDA_LOC="/scratch2/aherzog/CLDA/plda+/mpi_lda"
PLDA_CHUNKS=4
PLDA_ITERS=1000
PLDA_CPUS=12

PLDA_INFER_LOC="/scratch2/aherzog/CLDA/plda+/infer"
PLDA_INFER_ITERS=500
PLDA_INFER_BURN_IN=250

KMEANS_LOC="/scratch2/aherzog/CLDA/kmeans/seq_main"
KMEANS_THRESHOLD=0.001
